spring.application.name=AntiFraudSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/antifrauddb
spring.datasource.username=postgres
spring.datasource.password=hung14032004

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true