spring.application.name=AntiFraudSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/antifrauddb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true